### ISSUE TITLE
HA 0.89.2 使用aligenie报错哈

### ISSUE THREAD

**Issue by jamesho0** [Yonsm/HAExtra#7]
用frp穿透 HA 0.89.2 配置完成后 在获取设备处报错了。

2019-03-16 10:01:56 INFO (MainThread) [custom_components.aligenie] Handle Request: {'header': {'name': 'DiscoveryDevices', 'messageId': '7d3453d-b442-4e96-ae3d-2fd2e4564fce5', 'namespace': 'AliGenie.Iot.Device.Discovery', 'payLoadVersion': 1}, 'payload': {'accessToken': 'eyJ0eXAiOiJKV1QiLCJ565frrerDfff9.eyJleHAiOjE1ODQyMzc3MTIsImlhdCI6MTU1MjcwMTcxMiwiaXNzIjoiYjIyY2VkNDBhYzI3NGRmMGE5MDUzMWQyNzE1ZGFlYzMifQ._Pxaw3KJZQZQRpUhoEw5Bcfrrgw45wrAnDOUw'}}
2019-03-16 10:01:57 ERROR (MainThread) [custom_components.aligenie] Traceback (most recent call last):
  File "/home/pi/.homeassistant/custom_components/aligenie.py", line 106, in handleRequest
    result = discoveryDevice()
  File "/home/pi/.homeassistant/custom_components/aligenie.py", line 169, in discoveryDevice
    deviceName = guessDeviceName(entity_id, attributes, places, aliases)
  File "/home/pi/.homeassistant/custom_components/aligenie.py", line 373, in guessDeviceName
    if name == aliases['key'] or name in aliases['value']:
TypeError: list indices must be integers or slices, not str

**Comment by jamesho0** [comment]
修改第373行：
 if name == alias['key'] or name in alias['value']:

解决  可以获取设备了。

**Comment by jamesho0** [comment]
friendly_name  0.89已结不支持了 行362需要修改
    改name = attributes['friendly_name']
    为name = attributes['name']

**Comment by fireinice** [comment]
借问一下有没有碰到天猫精灵平台返回token不正确的问题？:(

**Comment by jamesho0** [comment]
> 借问一下有没有碰到天猫精灵平台返回token不正确的问题？:(

出现过一次  再刷新就没有了， 可能是网速慢了 没响应到数据的问题

**Comment by fireinice** [comment]
多谢，在home-assistant日志里能看到对auth/token的访问么？我这里好像只能看到对auth/authorize的访问，怎么刷似乎都不行。

**Comment by lulee007** [comment]
错误在这 373 行：
```py
# Name validation
   for alias in aliases:
     if name == aliases['key'] or name in aliases['value']:
```
应该为：
```py
# Name validation
   for alias in aliases:
     if name == alias['key'] or name in alias['value']:
```

**Comment by Yonsm** [comment]
妈呀真的是，感谢反馈，已更新。但是话说，我都不启用别名检查啊，地址全部用小写，关闭别名检查
